server:
  port: 8085

spring:
  application:
    name: ai-service

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3.2
        temperature: 0.3
        num-predict: 120
        num-ctx: 4096

      embedding:
        model: nomic-embed-text

    vectorstore:
      chroma:
        client:
          base-url: http://localhost:8000
        collection-name: enterprise-knowledge
        initialize-schema: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  endpoint:
    health:
      show-details: always

jwt:
  secret: enterprise-ai-platform-secret-key-change-this-in-production-2026