server:
  port: 8085

spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:mysql://localhost:3307/enterprise_ai
    username: enterprise
    password: enterprise

  ai:
    chat:
      options:
        temperature: 0.2

eems:
  ai:
    rag:
      top-k: 5
      similarity-threshold: 0.75

    assistant:
      max-conversation-messages: 20