server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/enterprise_ai
    username: enterprise
    password: enterprise

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eems:
  security:
    jwt:
      expiration-minutes: 30