server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/enterprise_ai
    username: enterprise
    password: enterprise

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: enterprise-ai-platform-secret-key-2026-secure-jwt-key
  expiration: 1800000